name: DYMO Labels
version: "1.0.0"
slug: dymo-labels
description: Print 300 DPI labels on a USB DYMO LabelWriter
url: https://github.com/home-assistant/addons-example
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
startup: services
boot: auto
init: false
ingress: true
ingress_port: 8099
panel_icon: mdi:label
ports:
  8099/tcp: null
usb: true
map:
  - addon_config:rw
options:
  backend: direct
  device: /dev/usb/lp0
  cups_printer: DYMO
schema:
  backend: list(direct|cups)
  device: str
  cups_printer: str